encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("add/", views.add_entry, name="add_entry"),
    path("edit/", views.edit, name="edit"),
    path("save/", views.save_edit, name="save_edit"),
    path("random/", views.random_page, name="random_page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from markdown2 import Markdown
from . import util
from random import choice

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def convert_md_to_html(title):
    content = util.get_entry(title)
    markdowner = Markdown()

    if content is None:
        return None
    else:
        return markdowner.convert(content)

def entry(request, title):
    html_content = convert_md_to_html(title)
    if html_content is None:
        return render(request, "encyclopedia/error.html", {
            "message": f'The requested page "{title}" was not found in encyclopedia'
        })
    else:
        return render(request, "encyclopedia/entry.html", {
            "title": title,
            "content": html_content
        })

def search(request):
    if request.method == "POST":
        entry_search = request.POST['search_query']
        html_content = convert_md_to_html(entry_search)

        if html_content is not None:
            return render(request, "encyclopedia/entry.html", {
                "title": entry_search,
                "content": html_content
            })
        else:
            recommendations = [entry for entry in util.list_entries() if entry_search.lower() in entry.lower()]
            return render(request, "encyclopedia/search.html", {
                "recommendations": recommendations,
                "entry_search": entry_search
            })
    else:
        return redirect("encyclopedia:index")
    
def add_entry(request):
    if request.method == "GET":
        return render(request, "encyclopedia/new_entry.html")
    else:
        title = request.POST['title']
        content = request.POST['content']
        already_exists = util.get_entry(title)

        if already_exists is not None:
            return render(request, "encyclopedia/error.html", {
                "message": f'The page with the title "{title}" already exists.'
            })
        else:
            util.save_entry(title, content)
            return redirect("encyclopedia:entry", title=title)
    
def edit(request):
    if request.method == "POST":
        title = request.POST['title']
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "content": content
        })
    else:
        return redirect("encyclopedia:index")
    
def save_edit(request):
    if request.method == "POST":
        title = request.POST['title']
        content = request.POST['content']
        util.save_entry(title, content)
        return redirect("encyclopedia:entry", title=title)
    else:
        return redirect("encyclopedia:index")
    
def random_page(request):
    random_entry = choice(util.list_entries())
    return redirect("encyclopedia:entry", title=random_entry)

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    <form action="{% url 'encyclopedia:save_edit' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title:</label>
            <input class="form-control" type="text" name="title" placeholder="Enter a title" value="{{ title }}" readonly>
        </div>
        <div class="form-group">
            <label for="content">Markdown Content:</label>
            <textarea class="form-control form-control-lg" name="content" id="content" placeholder="Enter markdown content">{{ content }}</textarea>
        </div>
        <input class="btn btn-success" type="submit" value="Save">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    <p>{{ content | safe }}</p>
    <form action="{% url 'encyclopedia:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}">
        <input class="btn btn-danger" type="submit" value="Edit Page">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Error</h1>
    <p>{{ message }}</p>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="search_query" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>New Page</h1>
    <form action="{% url 'encyclopedia:add_entry' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title:</label>
            <input class="form-control" type="text" name="title" placeholder="Enter a title">
        </div>
        <div class="form-group">
            <label for="content">Markdown Content:</label>
            <textarea class="form-control form-control-lg" name="content" id="content" placeholder="Enter markdown content"></textarea>
        </div>
        <input class="btn btn-primary" type="submit" value="Add New Page">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
{% if recommendations %}
    <ul>
        {% for entry in recommendations %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>Nothing related to "{{ entry_search }}" was found</p>
{% endif %}

{% endblock %}